#!/usr/bin/env ruby
require 'pathname'
require 'socket'
require 'json'

class Builder

  def run
    time_elapsed do
      setup_config
      set_use_cache
      checkout
      change_workdir
      install_vendor
      compile_assets
      restart_server
    end
  end

  def time_elapsed
    time = Time.now
    yield
    min, sec = (Time.now.to_f - time.to_f).divmod(60.0)
    puts('Time used: %3d:%04.2f' % [min.to_i, sec])
  end

  def setup_config
    @home = Pathname.new(ENV['HOME'])
    @pwd = Pathname.new(Dir.pwd).dirname
    @name = @pwd.basename
    ENV['GIT_DIR']       = (@gitdir  = @pwd + 'git').to_s
    ENV['GIT_WORK_TREE'] = (@workdir = @pwd + 'repo').to_s
    @vendor_src = @workdir + 'node_modules'
    @vendor_dst = @pwd + 'node_modules'
    @vendor_pivot = 'package.ls'
    @vendor_assets_pivot = 'bower.ls'
    setup_path
  end

  def setup_path
    path = JSON.parse(File.read(@home + 'PATH.json'))
    ENV['PATH'] = (path << ENV['PATH']).join(?:)
  end

  def set_use_cache
    @use_vendor_cache        = use_cache?(@vendor_pivot)
    @use_vendor_assets_cache = use_cache?(@vendor_assets_pivot)
  end

  def use_cache?(pivot)
    use_cache = false
    if (`git branch`.size > 0 &&
        `git ls-tree HEAD --name-only`[/^#{pivot}$/] &&
        (pivot_path = @workdir + pivot).exist?)
      old = File.read(pivot_path)
      `git checkout HEAD #{pivot}`
      new = File.read(pivot_path)
      use_cache = old == new
    end
    use_cache
  end

  def checkout
    reuse_vendor do
      `git clean -fd`
      `git checkout HEAD -f`
    end
  end

  def reuse_vendor
    if @vendor_src.exist?
      `mv #{@vendor_src} #{@vendor_dst}`
      yield
      `mv #{@vendor_dst} #{@vendor_src}`
    else
      yield
    end
  end

  def change_workdir
    Dir.chdir(@workdir)
  end

  def install_vendor
    if @use_vendor_cache
      puts 'Use vendor cache'
    else
      system("lsc #{@vendor_pivot}")
      system("lsc #{@vendor_assets_pivot}")
      system('npm install --production -q')
      system('npm prune')
    end
  end

  def compile_assets
    if @use_vendor_assets_cache
      puts 'Use vendor assets cache'
    else
      system('npm run assets:precompile:vendor')
    end
    system('npm run assets:precompile:app')
  end

  def restart_server
    port = File.read(@home + 'observer_port' + @name).to_i
    socket = TCPSocket.new(@name.to_s, port)
    socket.puts('kill')
    print socket.gets
    socket.puts('run')
    print socket.gets
    socket.puts('exit')
  end
end

Builder.new.run
