#!/usr/bin/env ruby
require_relative '../lib'
require_relative '../airweb'

class AirwebNode < Node

  class << self

    def create
      new({
        name: Airweb.user
      }, [], {
        from: 'archlinux',
        uid: '1012'
      })
    end
  end

  include Compilers
  include Observer

  def port
    {web_port => web_port,
     observer_port => observer_port}
  end

  def web_port;      '54276' end
  def observer_port; '54494' end

  def host_env
    observer_envp = {
      PORT: web_port,
      NODE_ENV: 'production',
      SSL_CRT: pwd + ssl_path + 'server.crt',
      SSL_KEY: pwd + ssl_path + 'server.key',
      SESSION_SECRET: SecureRandom.base64
    }
    observer_bind = {
      PG_CONN:    'PG_ENV_CONN',
      REDIS_HOST: 'REDIS_ENV_ADDR',
      REDIS_PORT: 'REDIS_ENV_PORT'
    }
    observer_envp.merge(observer_bind).merge(
      OBSERVER_ADDR: '0.0.0.0',
      OBSERVER_PORT: observer_port,
      OBSERVER_CWD:  repo_path,
      OBSERVER_EXEC: pwd + node_path,
      OBSERVER_ARGV: 'server/app.js',
      OBSERVER_ENVP: (observer_envp.keys + %w(PATH)).join(?:),
      OBSERVER_BIND: observer_bind.keys.join(?:)
    )
  end

  def links
    [['airweb_postgres', Airweb.dbaddr], ['airweb_redis', Airweb.session_addr]]
  end

  def generate
    generate_header
    create_user
    install_gcc
    as_user do
      install_nvm
      configure_observer
      generate_interface
    end
  end

  def create_user
    run('groupadd', '-g', gid, name)
    run('useradd', '-u', uid, '-g', gid, '-m', '-s /sbin/nologin', name)
  end

  def install_gcc
    run('pacman', '-Syy')
    run('pacman', '-S', '--noconfirm', 'gcc')
  end

  def generate_interface
    cmd(pwd + observer_path.basename(observer_path.extname))
  end

  def repo_path; Pathname.new('repo') end
  def ssl_path;  Pathname.new('ssl') end

  def volume
    [repo_path, ssl_path].map { |path| [pwd + path, host_pwd + path, 'ro'] }
  end

  def volume_exclude
    [repo_path, ssl_path]
  end

  def dependent_volume_setup?
    true
  end

  def volume_setup?
    (node_pwd + repo_path).exist?
  end

  def setup_volume
    mkdir(node_pwd + repo_path)
  end

  def clean_volume
    rmdir(node_pwd + repo_path)
  end
end
