#!/usr/bin/env ruby
require_relative '../postgres'
require_relative '../airweb'

class AirwebPostgresNode < PostgresNode

  def dbaddr; Airweb.dbaddr end
  def dbuser; Airweb.user   end
  def dbname; Airweb.dbname end
end
